### ISSUE TITLE
Error on activating the add-on

### ISSUE THREAD

**Issue by nielsmedemblik** [eaxum/nagato#10]
Hi I'm getting this error everytime when I try to activate the add-on, Am I missing some dependancies? The log is from 2.93 I also tested 2.91.

`
C:\Program Files\Blender Foundation\Blender 2.93>blender
Read prefs: C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\2.93\config\userpref.blend
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'nagato'
addon_utils.disable: nagato not disabled
Modules Installed (nagato) from 'C:\\Users\\Gebruiker\\Downloads\\nagato_0_2_5.zip' into 'C:\\Users\\Gebruiker\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons'
C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\nagato\__init__.py:74: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  destination_pysvn = bpy.app.binary_path_python + '/../../lib/site-packages/pysvn'
C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\nagato\__init__.py:75: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  destination_gazu = bpy.app.binary_path_python + '/../../lib/site-packages/gazu'
Saved session recovery to 'C:\Users\GEBRUI~1\AppData\Local\Temp\quit.blend'
Writing userprefs: 'C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\2.93\config\userpref.blend' ok
Error: Not freed memory blocks: 10, total unfreed memory 0.000736 MB
`

**Comment by Aderemi-Adesada** [comment]
bug has been fixed on latest release https://github.com/eaxum/nagato/releases/tag/v0.3.1

**Comment by nielsmedemblik** [comment]
Thanks for the help! But having another error now. Again on activation happing in atleast 2.91 2.92 and 2.93. 
```
Read prefs: C:\Users\niels\AppData\Roaming\Blender Foundation\Blender\2.92\config\userpref.blend
loading in background
<bpy_struct, WindowManager("WinMan") at 0x00000274693DD058>
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-2.92.0\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\niels\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\nagato\__init__.py", line 27, in <module>
    globals()[currentModuleFullName] = importlib.import_module(currentModuleFullName)
  File "C:\Program Files\Blender Foundation\blender-2.92.0\2.92\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\niels\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\nagato\svn.py", line 11, in <module>
    from . import pysvn
  File "C:\Users\niels\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\nagato\pysvn\__init__.py", line 116, in <module>
    add_dll_handle = os.add_dll_directory( os.path.dirname( __file__ ) )
AttributeError: module 'os' has no attribute 'add_dll_directory'
```

**Comment by Aderemi-Adesada** [comment]
the new version is only compatible with blender 2.93+

**Comment by Aderemi-Adesada** [comment]
pls try again installing nagato v0.3.1 on blender 2.93 LTS

**Comment by nielsmedemblik** [comment]
Nice it works! Sorry my intial respone was wrong I tested not 2.93.
