### ISSUE TITLE
Progress bar broken

### ISSUE THREAD

**Issue by Taiwofolu** [eaxum/nagato#18]
Nagato throws this error when I try to download project files with Blender 3.1

`Python: Traceback (most recent call last):
  File "C:\Users\..\Blender_Foundation\Blender Add-ons\scripts\addons\nagato\svn\operators.py", line 1309, in modal
    context.scene.progress_bar = percentage
TypeError: bpy_struct: item.attr = val: Scene.progress_bar expected an int type, not float

location: <unknown location>:-1

`

The download still completes but there's no indication of what's going on.

**Comment by Aderemi-Adesada** [comment]
it has been fixed
