### ISSUE TITLE
How to make add-on work?

### ISSUE THREAD

**Issue by 0anion0** [eaxum/nagato#2]
I cannot get the addon to work.
After installation, I entered the url of kitsu server api. (it works)
Where to enter the SVN address?(found)
errors appear periodically: "Not a working copy", "No tree can be found for given project."

**Comment by Aderemi-Adesada** [comment]
the add-on have a desktop app for setting up projects, from there you can set your svn repo location and configure file tree.
this is the link to the installer https://drive.google.com/file/d/1vALLltYWn2dyBzVrR9d41jMHWFHApYQp/view?usp=sharing.
thanks for the feed back

**Comment by 0anion0** [comment]
Thanks!

In kitsu-web I can create the episodes, the sequences, and shots.
What does "Scene" mean?

"sequences" is the rendering result?

**Comment by Taiwofolu** [comment]
'Scenes' here is the same as 'sequences' in Kitsu web. So 'Sequence 01' in Kitsu web is 'Scene 01' in your project directory.

**Comment by 0anion0** [comment]
In desktop app, there is sequence and scene when editing file tree.
> 'Scenes' here is the same as 'sequences' in Kitsu web.

What does "Scene" mean and what does "sequence" mean in desktop app?

[Specifications Gazu](https://gazu.cg-wire.com/specs.html):
> The client is divided in eight modules:
> ...
> shot: functions related to shots, sequences and episodes.
> scene: functions related to layout scenes (which will lead to shots).
> ...

Maybe I do not quite understand something in English. Sorry for the translation.

**Comment by Aderemi-Adesada** [comment]
Scenes is just a folder that house all scenes and sequences, the folder structure follows that of blender foundation.
